# Copyright 2021 Canonical
# See LICENSE file for licensing details.

options:
  public-hostname:
    type: string
    default:
    description: |
      The hostname or address of the public endpoints created for the
      dashboard
