{
 "title": "OSD device details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_metadata,ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$osd Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{ceph_daemon=~\"$osd\"}[$__rate_interval]) / on (ceph_daemon) rate(ceph_osd_op_r_latency_count[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{ceph_daemon=~\"$osd\"}[$__rate_interval]) / on (ceph_daemon) rate(ceph_osd_op_w_latency_count[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$osd R/W IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r{ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(ceph_osd_op_w{ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "$osd R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_out_bytes{ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(ceph_osd_op_w_in_bytes{ceph_daemon=~\"$osd\"}[$__rate_interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "Physical Device Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Physical Device Latency for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "(label_replace(rate(node_disk_read_time_seconds_total[$__rate_interval]) / rate(node_disk_reads_completed_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"))",
     "legendFormat": "{{instance}}/{{device}} Reads"
    },
    {
     "expr": "(label_replace(rate(node_disk_write_time_seconds_total[$__rate_interval]) / rate(node_disk_writes_completed_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\"))",
     "legendFormat": "{{instance}}/{{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device R/W IOPS for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(node_disk_writes_completed_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}} on {{instance}} Writes"
    },
    {
     "expr": "label_replace(rate(node_disk_reads_completed_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}} on {{instance}} Reads"
    }
   ]
  },
  {
   "title": "Physical Device R/W Bytes for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(node_disk_read_bytes_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{instance}} {{device}} Reads"
    },
    {
     "expr": "label_replace(rate(node_disk_written_bytes_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{instance}} {{device}} Writes"
    }
   ]
  },
  {
   "title": "Physical Device Util% for $osd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(node_disk_io_time_seconds_total[$__rate_interval]), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\") and on (instance, device) label_replace(label_replace(ceph_disk_occupation_human{ceph_daemon=~\"$osd\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance\", \"$1\", \"instance\", \"([^:.]*).*\")",
     "legendFormat": "{{device}} on {{instance}}"
    }
   ]
  }
 ]
}