{
 "title": "Ceph Pools Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "topk", "label": "Top K", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "topk($topk,rate(ceph_pool_rd[$__rate_interval]) + on(pool_id) group_left(instance,name) ceph_pool_metadata) ",
     "legendFormat": "{{name}} - read"
    },
    {
     "expr": "topk($topk,rate(ceph_pool_wr[$__rate_interval]) + on(pool_id) group_left(instance,name) ceph_pool_metadata) ",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Throughput by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Writes (+)" }
   ],
   "targets": [
    {
     "expr": "topk($topk,rate(ceph_pool_rd_bytes[$__rate_interval]) + on(pool_id) group_left(instance,name) ceph_pool_metadata)",
     "legendFormat": "{{name}} - read"
    },
    {
     "expr": "topk($topk,rate(ceph_pool_wr_bytes[$__rate_interval]) + on(pool_id) group_left(instance,name) ceph_pool_metadata)",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Client IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk($topk,((rate(ceph_pool_rd[$__rate_interval]) + rate(ceph_pool_wr[$__rate_interval])) + on(pool_id) group_left(instance,name) ceph_pool_metadata))"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "topk($topk,(rate(ceph_pool_rd_bytes[$__rate_interval]) + rate(ceph_pool_wr_bytes[$__rate_interval])) + on(pool_id) group_left(instance,name) ceph_pool_metadata) "
    }
   ]
  },
  {
   "title": "Top $topk Pools By Capacity Used",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "topk($topk,((ceph_pool_stored / (ceph_pool_stored + ceph_pool_max_avail)) * on(pool_id) group_left(name) ceph_pool_metadata))"
    }
   ]
  }
 ]
}