{
 "title": "RBD Overview",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_ops[$__rate_interval])))",
     "legendFormat": "Writes"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_ops[$__rate_interval])))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_bytes[$__rate_interval])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_bytes[$__rate_interval])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_rbd_write_latency_sum[$__rate_interval])) / sum(rate(ceph_rbd_write_latency_count[$__rate_interval])))",
     "legendFormat": "Write"
    },
    {
     "expr": "round(sum(rate(ceph_rbd_read_latency_sum[$__rate_interval])) / sum(rate(ceph_rbd_read_latency_count[$__rate_interval])))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Highest IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, (sort((rate(ceph_rbd_write_ops[$__rate_interval]) + on (image, pool, namespace) rate(ceph_rbd_read_ops[$__rate_interval])))))"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, sort(sum(rate(ceph_rbd_read_bytes[$__rate_interval]) + rate(ceph_rbd_write_bytes[$__rate_interval])) by (pool, image, namespace)))"
    }
   ]
  },
  {
   "title": "Highest Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    rate(ceph_rbd_write_latency_sum[$__rate_interval]) / clamp_min(rate(ceph_rbd_write_latency_count[$__rate_interval]), 1) +\n    rate(ceph_rbd_read_latency_sum[$__rate_interval]) / clamp_min(rate(ceph_rbd_read_latency_count[$__rate_interval]), 1)\n  ) by (pool, image, namespace)\n)"
    }
   ]
  }
 ]
}